baseURL = "https://jfx.ac/"
title = "jfx's site"
description = "my personal website"
pygmentsUseClasses = true
# uglyurls = true
disablePathToLower = false
rssLimit = 10

[permalinks]
blog = "/blog/:contentbasename"

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
ordered = true
